=== ZakariaOuakrim/Code_Generator_Back_End/json_schema2.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "title":"Class",
  "description": "Class information",  
  
  "required": ["package_name","name","table_name","annotations","properties","methods"],

  "properties": {
    "package_name": {
      "type": "string"
    },
    "name": {
      "type": "string",
      "pattern": "^[a-zA-Z]+"
    },
    "table_name": {
      "type": "string"
    },
    "annotations": {
      "type": "object",
      "properties": {
        "is_Entity": {
          "type": "boolean"
        }
      },
      "required": [
        "is_Entity"
      ]
    },
    "properties": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "is_injected": {
              "type": "boolean"
            },
            "name": {
              "type": "string",
              "pattern": "^[a-zA-Z]+"
            },
            "type": {
              "type": "string"
            }
          },
          "required": [
            "is_injected",
            "name",
            "type"
          ]
        },
        {
          "type": "object",
          "properties": {
            "column_name": {
              "type": "string"
            },
            "is_primary_key": {
              "type": "boolean"
            },
            "name": {
              "type": "string"
            },
            "type": {
              "type": "string"
            }
          },
          "required": [
            "column_name",
            "is_primary_key",
            "name",
            "type"
          ]
        },
        {
          "type": "object",
          "properties": {
            "column_name": {
              "type": "string"
            },
            "name": {
              "type": "string"
            },
            "type": {
              "type": "string"
            }
          },
          "required": [
            "column_name",
            "name",
            "type"
          ]
        }
      ]
    },
    "methods": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "name": {
              "type": "string"
            },
            "return_type": {
              "type": "string"
            },
            "parameters": {
              "type": "array",
              "items": [
                {
                  "type": "object",
                  "properties": {
                    "name": {
                      "type": "string"
                    },
                    "type": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "name",
                    "type"
                  ]
                },
                {
                  "type": "object",
                  "properties": {
                    "name": {
                      "type": "string"
                    },
                    "type": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "name",
                    "type"
                  ]
                }
              ]
            },
            "text": {
              "type": "string"
            }
          },
          "required": [
            "name",
            "return_type",
            "parameters",
            "text"
          ]
        }
      ]
    }
  }
}

=== ZakariaOuakrim/Code_Generator_Back_End/example_2.json
[{  
  "package_name": "com.example",
  "name": "Person",   
  "table_name":"person_table",
  "annotations":{
    "is_Entity":true
  },
  "properties":[
    {
      "is_injected":true,
      "name": "name",
      "type": "String"
    },
    {
      "column_name":"age_student",
      "is_primary_key":true,
      "name":"age",
      "type":"int"
    },
    {
      "column_name":"adress",
      "name":"adress",
      "type":"String"
    }
  ],
  "methods":[
   {
      "name":"Speak",
      "return_type":"String",
      "parameters":[
        {
          "name":"name",
          "type":"speach"
        },
        {
          "name":"age",
          "type":"int"
        }
      ],
      "text":"return speach;"
    }
  ]
},  
  {

    "package_name": "com.example",
    "name": "Student",
    "table_name":"student_table",
    "annotations":{
      "is_Entity":false,
      "is_Repository":true,
      "is_Service":true,
      "is_Controller":true,
      "is_Component":true
    },
    "properties": [
      {
        "is_injected":true,
        "name": "name",
        "type": "String"
      },
      {
        "column_name":"id_student",
        "is_primary_key":true,
        "column_name":"id_student",
        "name":"id",
        "type":"int"
      },
      {
        "column_name":"adress",
        "name":"adress",
        "type":"String"
      }
    ],
    "methods":[
      {
        "name":"Speak",
        "return_type":"String",
        "parameters":[
          {
            "name":"name",
            "type":"speach"
          },
          {
            "name":"age",
            "type":"int"
          }
        ],
        "text":"return speach;"
      }
    ]
    
  }

]
